name: Deploy AWS ECS with Terraform


on:
  workflow_run:
    workflows: ["Deployment"]
    types:
      - completed

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  security-events: write  


jobs:
  deploy:
    name: Deploy AWS ECS with Terraform
    runs-on: ubuntu-latest
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      contains(fromJSON('["main","staging","dev"]'), github.event.workflow_run.head_branch)
    environment: >-
      ${{ github.event.workflow_run.head_branch == 'main' && 'production' ||
          github.event.workflow_run.head_branch == 'staging' && 'staging' ||
          'dev' }}
    env:
      TF_ENV: >-
        ${{ github.event.workflow_run.head_branch == 'main' && 'production' ||
            github.event.workflow_run.head_branch == 'staging' && 'staging' ||
            'dev' }}


    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="env/${{ env.TF_ENV }}.backend.tfvars"

      - name: Terraform Plan
        run: terraform plan -var-file="env/${{ env.TF_ENV }}.tfvars" -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan